apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  type: NodePort
  ports:
    - name: "web-app-service"
      port: 4200
      targetPort: 4200
  selector:
    app: webapp
